= Backoff

A _backoff_ is an algorithm which introduces a delay between requests in a <<Retry>> <<amazon>>.

== Purpose

Backoff is used to protect services from retry traffic, especially when their availability is already compromised due to high load. This helps services recover and improves availability to clients.

Traffic from client retry attempts places strain on service providers such that their availability may suffer, especially if they are already strained by other traffic <<amazon>>. Backoff protocols cause clients to "back off" or reduce their request rate after each failed attempt, which helps services recover from load-related outages <<amazon>>.

NOTE: (TODO) This use-case is similar to that of a rate-limiter or circuit breaker.

== Risks

During an outage, fast-growing backoff algorithms can cause clients to spend a lot of time waiting between requests. <<amazon>> recommends placing a limit or "cap" on the maximum delay between requests, as in _capped exponential backoff_. While this limits the maximum delay, however, clients will continue to make retry requests at the same average rate once they hit their cap, which is contrary to the intent of backoff. <<amazon>> limits the maximum number of retries to avoid this case.

NOTE: (TODO) Since repeated retry attempts at a constant rate are undesirable, the advice from this section appears to be to always limit the number of retries rather than capping the backoff. We should tie in TCP backoff algorithm research here which might lend some mathematical insight to the problem.

- binary exponential backoff has known throughput problems in TCP contexts
- poor timeout or rate-limit settings may lead to spurious retry attempts / backoff, harming client throughput

== Characteristics 

- stability: a protocol is _stable_ if the average time until any message is delivered is _finite_, and if the time until the system processes all messages is also finite. That is, an unstable protocol will cause message buffers to grow without bound, and waiting time to grow without bound. [1]

- capacity: the capacity of a protocol is the greatest throughput it can achieve. [2] A protocol is said to achieve throughput λ if, when it runs with a input rate λ,the average success rate is λ. [2] This implies that if a service receives requests at rate λ but requests fail at an average rate n < λ, the throughput of the service is (λ - n), not λ.

== Notes

[1] https://core.ac.uk/reader/82629336
> Stability
> We use the standard model in which each client generatesrequests for a given server according to a Bernoulli distribu-tion  with  a  specified  mean.  Following  Ha#stad,  Leighton,and   Rogoff   [3],   we   say   that   a   contention-resolutionprotocol isstablefor the specified request rates if the expec-tation  of  the  average  waiting  time  incurred  by  a  messagebefore it is successfully delivered is finite and the expectationof  the  time  that  elapses  before  the  system  returns  to  theinitial state (in which there are no messages waiting in thebuffers) is also finite. It is easy to see that if a protocol is notstable  then  the  buffers  that  it  requires  to  store  waitingmessages grow larger and larger over time and the amountof time that it takes to send each message increases withoutbound.

[2] https://core.ac.uk/reader/208671266
"congestion collapse"
> One of the main goals of a congestion control algorithmis to protect the network againstcongestion collapse(e.g.,[16,26,36]) — an armageddonic scenario in which endpointssend packets at a high rate into the network, majority ofwhich gets dropped never reaching the destination.  As aresult, the network stays highly congested and useless, sincethe effective network throughput converges to zero. (p 19)

<<amazon>>
- *Exponential backoff* is a backoff strategy in which the delay between requests grows exponentially over time <<amazon>>.

"stability and capacity"
> Inthequeuingmodel of the backoff algorithm, it is assumedthat there areNusers, and useri(1≤i≤N) generatesa message independently in each step with probabilityλi.The total mean arrival rateλ=sigma(λi).
> The quality of a backoff protocol is measured by its stability and capacity. A backoff protocol is defined to be stable,for a given arrival rate λ, if the expected number of waiting messages over time is finite.  A protocol is said to achieve throughput λ if, when it runs with a input rate λ,the average success rate is λ. The capacity of a protocol is the maximum throughput it can achieve. Goldberget al.[17] prove the upper capacity bound for a shared-medium Eth-ernet backoff protocol. Kelly [24] shows no collision backoff slower than exponential guarantees stability on an Ethernet. Moreover, Aldous [4] shows that with infinite user population even exponential backoff will not guarantee stability for any positive arrival rate. (page 20)
* what are the implications of "infinite user population .... will not guarantee stability"?

https://arxiv.org/pdf/1208.6318.pdf
protocol fairness (HIGH capture by standard BEB)

https://core.ac.uk/download/pdf/4820304.pdf
(TODO)

http://people.cs.georgetown.edu/~jfineman/papers/backoff.pdf

> The  world  runs  on  exponential  backoff; nonetheless,  it  has  long  been  known  that  exponential backoff is [a]symptotically sub-optimal.

Stack Overflow (https://stackoverflow.com/a/28732630)

> Exponential back-off is useful in cases where simultaneous attempts to do something will interfere with each other such that none succeed. In such cases, having devices randomly attempt an operation in a window which is too small will result in most attempts failing and having to be retried. Only once the window has grown large enough will attempts have any significant likelihood of success.

> If one knew in advance that 16 devices would be wanting to communicate, one could select the size of window that would be optimal for that level of loading. In practice, though, the number of competing devices is generally unknown. The advantage of an exponential back-off where the window size doubles on each retry is that regardless of the number of competing entities:

    The window size where most operations succeed will generally be within a factor of two of the smallest window size where most operations would succeed,

    Most of the operations which fail at that window size will succeed on the next attempt (since most of the earlier operations will have succeeded, that will leave less than half of them competing for a window which is twice as big), and
    The total time required for all attempts will end up only being about twice what was required for the last one.

> If, instead of doubling each time, the window were simply increased by a constant amount, then the time spent retrying an operation until the window reached a usable size would be proportional to the square of whatever window size was required. While the final window size might be smaller than would have been used with exponential back-off, the total cost of all the attempts would be much greater.


Computer Networks, Fifth Ed. Tanenbaum and Wetherall
(https://raw.githubusercontent.com/gsahinpi/acm361/master/Computer%20Networks%20-%20A%20Tanenbaum%20-%205th%20edition.pdf)

> This algorithm, calledbinary exponential backoff, was chosen to dynami-cally adapt to the number of stationstrying to send. Ifthe randomizationintervalfor all collisions were 1023, the chance of two stations colliding for a second timewould be negligible, but the average waitafter a collision would be hundreds ofslot times, introducing significant delay. On theother hand, ifeachstation always
286THE MEDIUM ACCESS CONTROL SUBLAYERCHAP. 4delayed for either 0 or 1 slots, then if 100 stations ever tried to send at once theywould collide over and over until 99 of them picked 1 and the remaining stationpicked 0. This might take years. Byhaving therandomization intervalgrow ex-ponentially as more andmore consecutive collisions occur,the algorithm ensuresa low delay when only a few stationscollide but also ensures that the collisionsare resolved in a reasonable intervalwhen many stationscollide.Truncating thebackoff at 1023 keeps the bound from growing too large.

https://devopedia.org/binary-exponential-backoff

The "capture effect" is when a few nodes occupy a resource most of the time. In binary exponentil backoff, nodes which have collided enter backoff
