= Distributed Programming & Fault Tolerance

This repository consists of short essays and programming exercises in the field of distributed programming and fault tolerance.

:toc:

== Topics

* link:circuit-breaker[Circuit breaker], a fault-tolerance primitive that sheds load from struggling subsystems.
* link:rate-limiter[Rate limiter], a fault-tolerance primitive that prevents clients of a system from exceeding a sustainable request rate.

== Useful Libraries

=== Resilience4J

Resilience4J implements a number of useful fault-tolerance mechanisms like circuit breakers, bulkheads, and retry mechanisms. Resilience4j is inspired by Netflix's https://github.com/Netflix/Hystrix[Hystrix] library, which is no longer actively maintained but curates similar configuration-based mechanisms. As stated in the Hystrix README, Netflix is moving away from configuration-heavy strategies employed by Resilience4J and Hystix towards research on https://medium.com/@NetflixTechBlog/performance-under-load-3e6fa9a60581[adaptive concurrency limits].
