= Rate Limiter

Rate-limiters exist to protect services from unsustainable request volumes, such as during spikes in user traffic or denial-of-service attacks (including friendly-fire from misbehaving collaborator services) <<google-cloud>><<stripe>>. While services can utilize rate-limiting to protect themselves from high request volume, they can also use rate-limiting to control the volume of their own requests to unprotected legacy back-ends that are otherwise vulnerable <<google-cloud>>. In either case, rate-limiters deny requests above a certain throughput, shedding load off vulnerable systems, and may even prioritize certain types of requests over others to ensure less-significant systems degrade before more-critical systems <<stripe>>.

Clients of rate-limited systems should respond to rate-limiting intelligently or else risk https://landing.google.com/sre/sre-book/chapters/addressing-cascading-failures/[cascading failures] as errors from one service propagate uncontrolled throughout a network of collaborating services, possibly with self-reinforcing consequences <<google-cloud>>. In order for clients to respond to rate-limiting, services must signal clients when rate-limiting is active, such as by returning error code https://httpstatuses.com/429[429: Too Many Requests] <<getambassador>> during periods of high load. Clients will typically want to re-try rate-limited requests, though they should do so with exponential back-off and jitter to avoid the https://en.wikipedia.org/wiki/Thundering_herd_problem["thundering herd"] problem wherein many clients inadvertently synchronize their requests, sending their combined traffic all at once <<google-cloud>>. As an alternative to rejecting excessive requests, services may be able to enqueue them for asynchronous fulfillment. In this scenario a service would immediately return a job ID to the client in response to their request. The client would know to poll the service or subscribe to an appropriate messaging channel for the response <<resilience4j-ratelimiter>><<google-cloud>>.

Rate-limiting strategies which discard traffic in exceeds of an allowed rate (e.g. with 429 http responses) are referred to as _traffic policing_ strategies, and strategies which instead defer requests until they conform to a tolerable request rate (e.g. by enqueuing requests for asynchronous fulfillment) are referred to as _traffic shaping_ strategies <<rfc-2475>><<wikipedia-traffic-policing>>.

There are multiple algorithms for rate-limiting (see <<google-cloud>><<wikipedia-ratelimiting>>), some of which we will explore below.

== Token Bucket (Leaky Bucket) Algorithm

NOTE: There are two implementations of the leaky bucket, one used to police traffic, and one used to shape it. The version that is used to police traffic is conceptually the same as the token bucket; the amount to different mental models for the same algorithm. <<wikipedia-token-bucket>>

The token bucket algorithm is used to police or shape traffic to conform to a desired level of "burstiness" and average request rate <<science-direct>><<wikipedia-token-bucket>>. This strategy limits each request by the resources (e.g. database connections, CPU time) it requires such that overall traffic is limited on the basis of available system capacity rather than simple volume of requests <<google-cloud>>.

The algorithm is based on the analogy of a bucket filled with tokens. Requesters must retrieve some number of tokens from the bucket based on the capacity they wish to utilize. If the bucket has enough tokens, the requester removes the tokens and computes a response. If the bucket has too few tokens, the request is rejected or enqueued for later computation depending on implementation. At a fixed rate, tokens are added back to the bucket, but any excess tokens beyond the bucket's capacity are simply discarded <<google-cloud>><<cisco-token-bucket>><<wikipedia-token-bucket>>. The capacity of the bucket therefore determines the maximum instantaneous capacity that may be utilized by requests, and the rate at which tokens are added governs the long-term average utilization <<cisco-token-bucket>><<wikipedia-token-bucket>><<science-direct>>.

In telecommunications contexts, token buckets are often used to limit the average rate at which bits flow into a network with limited bandwidth <<cisco-token-bucket>><<wikipedia-token-bucket>><<science-direct>>. The literature describes such a token bucket algorithm with the equation `CIR = CBS * T` <<science-direct>>, where:
* `CIR`, the _committed information rate_ or _mean rate_, is the average rate at which bits are forwarded to the network;
* `CBS`, the _committed burst size_, is the maximum volume of bits submitted simultaneously during the time period `T`; and
* `T` is the maximum duration of a burst during which the network is fully utilized.

The capacity of a token bucket is represented by `CBS`; clients of the bucket can never request more than `CBS` tokens at a single time. Tokens are returned to the bucket at the rate `CIR`, which by definition means all `CBS` tokens are replenished every interval `T`. Therefore in the worst case, clients can request at most `CBS` tokens every interval `T`, which over the long-term conforms to the desired average request rate `CIR`.

== Examples

* link:example/general/index.adoc[Exploration of general rate-limiter usage.] Built with Java, Resilience4J, and Spring Boot.

* link:example/token-bucket/index.adoc[Implementations of the token bucket rate-limiter algorithm.] Built with Elixir using agents for distributed rate-limiting or atomics for fast local rate-limiting.

[bibliography]
== References
- [[[google-cloud, 1]]] "Rate-limiting strategies and techniques." Google Cloud. https://cloud.google.com/solutions/rate-limiting-strategies-techniques (accessed Aug. 8, 2020).
- [[[stripe, 2]]] P. Tarjan. "Scaling your API with rate limiters." Stripe. https://stripe.com/blog/rate-limiters (accessed Aug. 8, 2020).
- [[[getambassador, 3]]] D. Bryant. "Part 2: rate limiting for API gateways." Ambassador. https://blog.getambassador.io/rate-limiting-for-api-gateways-892310a2da02 (accessed Aug. 8, 2020).
- [[[resilience4j-ratelimiter, 4]]] "Ratelimiter." Resilience4j. https://resilience4j.readme.io/docs/ratelimiter (accessed Aug. 8, 2020).
- [[[rfc-2475, 5]]] S. Blake, D. Black, M. Carlson, E. Davies, Z.Wang, W. Weisss. "RFC 2475 - An Architecture for Differentiated Services." IETF Tools. https://tools.ietf.org/html/rfc2475#section-1.2 (accessed Sep. 7, 2020).
- [[[wikipedia-traffic-policing, 6]]] "Traffic policing (communications)." Wikipedia. https://en.wikipedia.org/wiki/Traffic_policing_(communications) (accessed Sep. 7, 2020).
- [[[wikipedia-ratelimiting, 7]]] "Rate limiting." Wikipedia. https://en.wikipedia.org/wiki/Rate_limiting (accessed Aug. 8, 2020).
- [[[wikipedia-token-bucket, 8]]] "Token bucket." Wikipedia. https://en.wikipedia.org/wiki/Token_bucket (accessed Sep. 7, 2020)
- [[[science-direct, 9]]] D. Medhi, K. Ramasamy, Network Routing, 2nd ed. Elsevier Inc, 2018, ch. 18.4.2, pp. 626-644. [Online]. Available: https://www.sciencedirect.com/topics/computer-science/token-bucket. Accessed: Sep. 7, 2020.
- [[[cisco-token-bucket, 10]]] "Policing and Shaping Overview." Cisco Networking Software. https://www.cisco.com/c/en/us/td/docs/ios/qos/configuration/guide/12_2sr/qos_12_2sr_book/polcing_shping_oview.html (accessed Sep 07, 2020).
